<h1>Project 2 Michael Felker, Gali Abrel, Komalpreet Sandhu, Joshua Santhumayor<h1>

<h1>Importing the Data<h1>

In [69]:
import pandas as pd

In [70]:
df = pd.read_csv('bank-sampled-9K.csv')
df

Unnamed: 0  age           job   marital  education default  balance  \
0              0   58    management   married   tertiary      no     2143   
1              2   33  entrepreneur   married  secondary      no        2   
2             11   29        admin.    single  secondary      no      390   
3             12   53    technician   married  secondary      no        6   
4             17   57   blue-collar   married    primary      no       52   
...          ...  ...           ...       ...        ...     ...      ...   
8995       45199   34   blue-collar    single  secondary      no     1475   
8996       45201   53    management   married   tertiary      no      583   
8997       45204   73       retired   married  secondary      no     2850   
8998       45206   51    technician   married   tertiary      no      825   
8999       45207   71       retired  divorced    primary      no     1729   

     housing loan   contact  day month  duration  campaign  pdays  previous  \
0        yes   no   unknown    5   may       261         1     -1         0   
1        yes  yes   unknown    5   may        76         1     -1         0   
2        yes   no   unknown    5   may       137         1     -1         0   
3        yes   no   unknown    5   may       517         1     -1         0   
4        yes   no   unknown    5   may        38         1     -1         0   
...      ...  ...       ...  ...   ...       ...       ...    ...       ...   
8995     yes   no  cellular   16   nov      1166         3    530        12   
8996      no   no  cellular   17   nov       226         1    184         4   
8997      no   no  cellular   17   nov       300         1     40         8   
8998      no   no  cellular   17   nov       977         3     -1         0   
8999      no   no  cellular   17   nov       456         2     -1         0   

     poutcome    y  
0     unknown   no  
1     unknown   no  
2     unknown   no  
3     unknown   no  
4     unknown   no  
...       ...  ...  
8995    other   no  
8996  success  yes  
8997  failure  yes  
8998  unknown  yes  
8999  unknown  yes  

[9000 rows x 18 columns]

<h1>droping duration column<h1>

In [71]:
df.drop('Unnamed: 0', axis=1, inplace=True)
df.drop('duration',axis=1, inplace=True)

<h1>convert two column time to number of dates until the last day of compaign<h1>

In [72]:
from datetime import datetime as dt
last_date="18 Nov, 2010"
date=dt.strptime(last_date, "%d %b, %Y")
date
df['month']=df['month'].apply(lambda x: x.capitalize())
df['date']= df['day'].astype(str)+" "+df['month'] + ", 2010"

df['last_contact']=df['date'].apply(lambda x:(date-dt.strptime(x, "%d %b, %Y")).days)

df.drop(columns={'day','date','month'}, axis=1, inplace=True)
df

age           job   marital  education default  balance housing loan  \
0      58    management   married   tertiary      no     2143     yes   no   
1      33  entrepreneur   married  secondary      no        2     yes  yes   
2      29        admin.    single  secondary      no      390     yes   no   
3      53    technician   married  secondary      no        6     yes   no   
4      57   blue-collar   married    primary      no       52     yes   no   
...   ...           ...       ...        ...     ...      ...     ...  ...   
8995   34   blue-collar    single  secondary      no     1475     yes   no   
8996   53    management   married   tertiary      no      583      no   no   
8997   73       retired   married  secondary      no     2850      no   no   
8998   51    technician   married   tertiary      no      825      no   no   
8999   71       retired  divorced    primary      no     1729      no   no   

       contact  campaign  pdays  previous poutcome    y  last_contact  
0      unknown         1     -1         0  unknown   no           197  
1      unknown         1     -1         0  unknown   no           197  
2      unknown         1     -1         0  unknown   no           197  
3      unknown         1     -1         0  unknown   no           197  
4      unknown         1     -1         0  unknown   no           197  
...        ...       ...    ...       ...      ...  ...           ...  
8995  cellular         3    530        12    other   no             2  
8996  cellular         1    184         4  success  yes             1  
8997  cellular         1     40         8  failure  yes             1  
8998  cellular         3     -1         0  unknown  yes             1  
8999  cellular         2     -1         0  unknown  yes             1  

[9000 rows x 15 columns]

In [73]:
df.describe()

age        balance     campaign        pdays     previous  \
count  9000.000000    9000.000000  9000.000000  9000.000000  9000.000000   
mean     41.035667    1372.970222     2.767667    39.906444     0.609556   
std      10.561698    3363.690197     3.011022    99.440498     3.499115   
min      18.000000   -4057.000000     1.000000    -1.000000     0.000000   
25%      33.000000      68.000000     1.000000    -1.000000     0.000000   
50%      39.000000     450.000000     2.000000    -1.000000     0.000000   
75%      48.000000    1453.250000     3.000000    -1.000000     0.000000   
max      90.000000  102127.000000    51.000000   831.000000   275.000000   

       last_contact  
count   9000.000000  
mean     150.289000  
std       74.721977  
min      -42.000000  
25%      104.000000  
50%      166.000000  
75%      193.000000  
max      316.000000

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   age           9000 non-null   int64 
 1   job           9000 non-null   object
 2   marital       9000 non-null   object
 3   education     9000 non-null   object
 4   default       9000 non-null   object
 5   balance       9000 non-null   int64 
 6   housing       9000 non-null   object
 7   loan          9000 non-null   object
 8   contact       9000 non-null   object
 9   campaign      9000 non-null   int64 
 10  pdays         9000 non-null   int64 
 11  previous      9000 non-null   int64 
 12  poutcome      9000 non-null   object
 13  y             9000 non-null   object
 14  last_contact  9000 non-null   int64 
dtypes: int64(6), object(9)
memory usage: 1.0+ MB


In [75]:


#drop columns individually that share attributes and get their dummie_values
contact_dummies=pd.get_dummies(df['contact'],prefix='contact',drop_first=True)
df.drop('contact',axis=1,inplace=True)
df=df.join(contact_dummies)
poutcome_dummies=pd.get_dummies(df['poutcome'],prefix='poutcome',drop_first=True)
df.drop('poutcome',axis=1,inplace=True)
df=df.join(poutcome_dummies)
y_dummies=pd.get_dummies(df['y'],prefix='y',drop_first=True)
df.drop('y',axis=1,inplace=True)
df=df.join(y_dummies)
housing_dummies=pd.get_dummies(df['housing'],prefix='housing',drop_first=True)
df.drop('housing',axis=1,inplace=True)
df=df.join(housing_dummies)
default_dummies=pd.get_dummies(df['default'],prefix='default',drop_first=True)
df.drop('default',axis=1,inplace=True)
df=df.join(default_dummies)
#drop the other ones
df = pd.get_dummies(df, columns=['job', 'marital', 'education', 'loan'], drop_first=True)
df.dropna(inplace=True)
df



age  balance  campaign  pdays  previous  last_contact  \
0      58     2143         1     -1         0           197   
1      33        2         1     -1         0           197   
2      29      390         1     -1         0           197   
3      53        6         1     -1         0           197   
4      57       52         1     -1         0           197   
...   ...      ...       ...    ...       ...           ...   
8995   34     1475         3    530        12             2   
8996   53      583         1    184         4             1   
8997   73     2850         1     40         8             1   
8998   51      825         3     -1         0             1   
8999   71     1729         2     -1         0             1   

      contact_telephone  contact_unknown  poutcome_other  poutcome_success  \
0                 False             True           False             False   
1                 False             True           False             False   
2                 False             True           False             False   
3                 False             True           False             False   
4                 False             True           False             False   
...                 ...              ...             ...               ...   
8995              False            False            True             False   
8996              False            False           False              True   
8997              False            False           False             False   
8998              False            False           False             False   
8999              False            False           False             False   

      ...  job_student  job_technician  job_unemployed  job_unknown  \
0     ...        False           False           False        False   
1     ...        False           False           False        False   
2     ...        False           False           False        False   
3     ...        False            True           False        False   
4     ...        False           False           False        False   
...   ...          ...             ...             ...          ...   
8995  ...        False           False           False        False   
8996  ...        False           False           False        False   
8997  ...        False           False           False        False   
8998  ...        False            True           False        False   
8999  ...        False           False           False        False   

      marital_married  marital_single  education_secondary  \
0                True           False                False   
1                True           False                 True   
2               False            True                 True   
3                True           False                 True   
4                True           False                False   
...               ...             ...                  ...   
8995            False            True                 True   
8996             True           False                False   
8997             True           False                 True   
8998             True           False                False   
8999            False           False                False   

      education_tertiary  education_unknown  loan_yes  
0                   True              False     False  
1                  False              False      True  
2                  False              False     False  
3                  False              False     False  
4                  False              False     False  
...                  ...                ...       ...  
8995               False              False     False  
8996                True              False     False  
8997               False              False     False  
8998                True              False     False  
8999               False              False     False  

[9000 rows x 31 columns]

In [76]:
#remake colums with - to _
df.rename(columns=lambda x: x.replace('-', '_'), inplace=True)

<h1>Scaling the data and seperating target variable and features<h1>

In [77]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel
import statsmodels.api as sm
import numpy as np


In [78]:

df = df.astype(float)

x = df.drop(['y_yes'], axis=1)
y = df['y_yes']

scaler = StandardScaler()
scaled_x=scaler.fit_transform(x)



<h1>use logistic regression to select features<h1>

In [79]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler


method = Pipeline([
    ('scaler', RobustScaler()),  
    ('feature_selection', SelectFromModel(estimator=LogisticRegression(max_iter=5000))),  # Feature selection
])

#method = SelectFromModel(estimator=LogisticRegression(max_iter=5000))
method.fit(x,y)
print(pd.DataFrame({'coef': method.named_steps['feature_selection'].estimator_.coef_[0], \
              'select_feature': method.named_steps['feature_selection'].get_support()},\
             index=x.columns)
     )
#df.info()
# 10 features


                         coef  select_feature
age                 -0.028827           False
balance              0.026110           False
campaign            -0.249123           False
pdays                0.000311           False
previous             0.004018           False
last_contact         0.074239           False
contact_telephone   -0.161771           False
contact_unknown     -0.982509            True
poutcome_other       0.224006           False
poutcome_success     2.278701            True
poutcome_unknown    -0.017697           False
housing_yes         -0.607431            True
default_yes         -0.271916           False
job_blue_collar     -0.072644           False
job_entrepreneur    -0.510568            True
job_housemaid       -0.709682            True
job_management      -0.272377           False
job_retired          0.644228            True
job_self_employed   -0.342569            True
job_services        -0.210750           False
job_student          0.292412     

In [80]:
#method.threshold_
#x2=method.transform(x)

#df=df.dropna()
#df
#df.info()

#sm_model= sm.GLM(y,x,family=sm.families.Binomial())
#sm_result = sm_model.fit(fit_intercept=True)





In [81]:
#Model2 - Linear SVC

from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC, SVC

svc = Pipeline([
    ('scaler', RobustScaler()), 
    ('feature_selection', SelectFromModel(LinearSVC(C=0.001)))
    
])

svc.fit(x,y)

c:\Python312\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('scaler', RobustScaler()),
                ('feature_selection',
                 SelectFromModel(estimator=LinearSVC(C=0.001)))])

In [82]:
import numpy as np
selected_features_svc = svc.named_steps['feature_selection'].get_support()
print(selected_features_svc)

print(np.count_nonzero(selected_features_svc))
#12 features selected


[False False False False False False False  True False  True  True  True
 False  True  True  True  True  True False  True False  True False False
 False False False False False  True]
12


In [83]:
#method 3

#Model3 SelectKBest

from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif

method3 = Pipeline([
    ('scaler', RobustScaler()), 
    ('feature_selection', SelectKBest(score_func=mutual_info_classif, k=10))
    
])

method3.fit(x,y)

method3.get_feature_names_out() 


#10 features

array(['age', 'balance', 'campaign', 'pdays', 'previous', 'last_contact',
       'contact_unknown', 'poutcome_success', 'poutcome_unknown',
       'loan_yes'], dtype=object)

In [84]:
print("the number of features:",len(method3.get_feature_names_out()))

the number of features  10


In [85]:
# the feature selection method that has the lowest number of features - Model1 and 3 had 10 >> LogisticRegression

#save the features:


selected_features = x.columns[method.named_steps['feature_selection'].get_support()]
print(selected_features)

df_selected_features = df[selected_features]
df_selected_features

Index(['contact_unknown', 'poutcome_success', 'housing_yes',
       'job_entrepreneur', 'job_housemaid', 'job_retired', 'job_self_employed',
       'education_tertiary', 'education_unknown', 'loan_yes'],
      dtype='object')


contact_unknown  poutcome_success  housing_yes  job_entrepreneur  \
0                 1.0               0.0          1.0               0.0   
1                 1.0               0.0          1.0               1.0   
2                 1.0               0.0          1.0               0.0   
3                 1.0               0.0          1.0               0.0   
4                 1.0               0.0          1.0               0.0   
...               ...               ...          ...               ...   
8995              0.0               0.0          1.0               0.0   
8996              0.0               1.0          0.0               0.0   
8997              0.0               0.0          0.0               0.0   
8998              0.0               0.0          0.0               0.0   
8999              0.0               0.0          0.0               0.0   

      job_housemaid  job_retired  job_self_employed  education_tertiary  \
0               0.0          0.0                0.0                 1.0   
1               0.0          0.0                0.0                 0.0   
2               0.0          0.0                0.0                 0.0   
3               0.0          0.0                0.0                 0.0   
4               0.0          0.0                0.0                 0.0   
...             ...          ...                ...                 ...   
8995            0.0          0.0                0.0                 0.0   
8996            0.0          0.0                0.0                 1.0   
8997            0.0          1.0                0.0                 0.0   
8998            0.0          0.0                0.0                 1.0   
8999            0.0          1.0                0.0                 0.0   

      education_unknown  loan_yes  
0                   0.0       0.0  
1                   0.0       1.0  
2                   0.0       0.0  
3                   0.0       0.0  
4                   0.0       0.0  
...                 ...       ...  
8995                0.0       0.0  
8996                0.0       0.0  
8997                0.0       0.0  
8998                0.0       0.0  
8999                0.0       0.0  

[9000 rows x 10 columns]

In [86]:
df_selected_features.to_csv('feature1.csv')

# Classifier Modelling

In [87]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [88]:
x = df_selected_features
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state = 42)

In [89]:
tree = DecisionTreeClassifier(random_state=0, max_depth=5)
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=0)

In [90]:
#tree = DecisionTreeClassifier(random_state=0, max_depth=5)

#scores=cross_val_score(tree,X_train,y_train, cv=4)
#print(scores)
#print(scores.mean())

In [91]:
from sklearn.model_selection import cross_val_score

#k-fold cross-validation (You can select the fold anywhere between 2 to 5)
k_folds = 4
cross_validation_scores_tree = cross_val_score(tree, X_train, y_train, cv=k_folds)

#calculate the mean
tree_mean = cross_validation_scores_tree.mean()
print(tree_mean)

0.8924454885000155


In [92]:
# Naïve Bayes classifier

from sklearn.naive_bayes import GaussianNB

naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)


GaussianNB()

In [93]:
cross_validation_scores_naive_bayes = cross_val_score(naive_bayes, X_train, y_train, cv=k_folds)
print(cross_validation_scores_naive_bayes)

nb_mean = cross_validation_scores_naive_bayes.mean()
print(nb_mean)

[0.86729858 0.86255924 0.8601067  0.86899822]
0.8647406849703757


In [94]:
# KNN
# class sklearn.neighbors.KNeighborsClassifier(n_neighbors=5, *, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

cross_validation_scores_knn = cross_val_score(knn, X_train, y_train, cv=k_folds)
print(cross_validation_scores_knn)

knn_mean = cross_validation_scores_knn.mean()
print(knn_mean)

[0.88981043 0.88329384 0.89448726 0.89626556]
0.8909642702629812


In [95]:
# Random forest
from sklearn.ensemble import RandomForestClassifier

# estimator between 10 to 1000
r_forest = RandomForestClassifier(n_estimators=300, max_depth=5, random_state=0)


cross_validation_scores_rf = cross_val_score(r_forest, X_train, y_train, cv=k_folds)
print(cross_validation_scores_rf)

rf_mean = cross_validation_scores_rf.mean()
print(rf_mean)    

[0.89691943 0.88329384 0.89626556 0.89567279]
0.8930379055616268


In [96]:
# the choosen is DecisionTreeClassifier

# Classifier Model – The Second Try

In [97]:
from sklearn.preprocessing import RobustScaler

x = df.drop(['y_yes'], axis=1)
y = df['y_yes']
#9 feature selection so there are less fetures selected in this version
method_with_randomForest = Pipeline([
    ('feature_selection', SelectFromModel(estimator=RandomForestClassifier(n_estimators=300, max_depth=5, random_state=0, max_features=9))),  
    ('scaler', RobustScaler())  
])

method_with_randomForest.fit(x,y)

print(pd.DataFrame({
              'select_feature': method_with_randomForest.named_steps['feature_selection'].get_support()},\
             index=x.columns)
     )

                     select_feature
age                            True
balance                        True
campaign                      False
pdays                          True
previous                       True
last_contact                   True
contact_telephone             False
contact_unknown                True
poutcome_other                False
poutcome_success               True
poutcome_unknown              False
housing_yes                    True
default_yes                   False
job_blue_collar               False
job_entrepreneur              False
job_housemaid                 False
job_management                False
job_retired                   False
job_self_employed             False
job_services                  False
job_student                   False
job_technician                False
job_unemployed                False
job_unknown                   False
marital_married               False
marital_single                False
education_secondary         

In [98]:
# saving the selected features to file 

df2_selected_features = df[selected_features]
df2_selected_features

contact_unknown  poutcome_success  housing_yes  job_entrepreneur  \
0                 1.0               0.0          1.0               0.0   
1                 1.0               0.0          1.0               1.0   
2                 1.0               0.0          1.0               0.0   
3                 1.0               0.0          1.0               0.0   
4                 1.0               0.0          1.0               0.0   
...               ...               ...          ...               ...   
8995              0.0               0.0          1.0               0.0   
8996              0.0               1.0          0.0               0.0   
8997              0.0               0.0          0.0               0.0   
8998              0.0               0.0          0.0               0.0   
8999              0.0               0.0          0.0               0.0   

      job_housemaid  job_retired  job_self_employed  education_tertiary  \
0               0.0          0.0                0.0                 1.0   
1               0.0          0.0                0.0                 0.0   
2               0.0          0.0                0.0                 0.0   
3               0.0          0.0                0.0                 0.0   
4               0.0          0.0                0.0                 0.0   
...             ...          ...                ...                 ...   
8995            0.0          0.0                0.0                 0.0   
8996            0.0          0.0                0.0                 1.0   
8997            0.0          1.0                0.0                 0.0   
8998            0.0          0.0                0.0                 1.0   
8999            0.0          1.0                0.0                 0.0   

      education_unknown  loan_yes  
0                   0.0       0.0  
1                   0.0       1.0  
2                   0.0       0.0  
3                   0.0       0.0  
4                   0.0       0.0  
...                 ...       ...  
8995                0.0       0.0  
8996                0.0       0.0  
8997                0.0       0.0  
8998                0.0       0.0  
8999                0.0       0.0  

[9000 rows x 10 columns]

In [99]:
df2_selected_features.to_csv('feature2.csv')

In [100]:
from sklearn.model_selection import cross_val_score

x = df2_selected_features
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state = 42)

tree = DecisionTreeClassifier(random_state=0, max_depth=5)
tree.fit(X_train, y_train)

#k-fold cross-validation (You can select the fold anywhere between 2 to 5)
k_folds = 4
cross_validation_scores_tree = cross_val_score(tree, X_train, y_train, cv=k_folds)

#calculate the mean
tree_mean = cross_validation_scores_tree.mean()
print(tree_mean)

0.8924454885000155


In [101]:

naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)

cross_validation_scores_naive_bayes = cross_val_score(naive_bayes, X_train, y_train, cv=k_folds)
print(cross_validation_scores_naive_bayes)

nb_mean = cross_validation_scores_naive_bayes.mean()
print(nb_mean)

[0.86729858 0.86255924 0.8601067  0.86899822]
0.8647406849703757


In [102]:

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

cross_validation_scores_knn = cross_val_score(knn, X_train, y_train, cv=k_folds)
print(cross_validation_scores_knn)

knn_mean = cross_validation_scores_knn.mean()
print(knn_mean)

[0.88981043 0.88329384 0.89448726 0.89626556]
0.8909642702629812


In [103]:
# Random forest
from sklearn.ensemble import RandomForestClassifier

# estimator between 10 to 1000
r_forest = RandomForestClassifier(n_estimators=300, max_depth=5, random_state=0)


cross_validation_scores_rf = cross_val_score(r_forest, X_train, y_train, cv=k_folds)
print(cross_validation_scores_rf)

rf_mean = cross_validation_scores_rf.mean()
print(rf_mean)    

[0.89691943 0.88329384 0.89626556 0.89567279]
0.8930379055616268


# References
    
 
https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html
    
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html